{
 "title": "Videokyc--Application Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(disk_free_bytes{businessunit=~\"banktech\"},application)"
    }
   },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"$application\"},environment)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{environment=\"$environment\"},job)"
    }
   },
   {
    "name": "kubernetes_namespace",
    "label": "kubernetes_namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{environment=\"$environment\"},kubernetes_namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(disk_free_bytes{job=\"$job\", application=\"$application\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,,2d,3d,4d,5d,6d,7d,14d,30d,60d"
   },
   {
    "name": "outbound_uri",
    "label": "Outbound_URI",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{environment=\"$environment\", application=\"$application\"},uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>Currently your are viewing <h1>$environment - $kubernetes_namespace</h1></center>"
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Event Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "p95 quantile agent consumer events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "videokyc_event_latency_metric_seconds{application=~\"$application\",uri!~\".*health.*|.*prom.*\",quantile=\"0.95\",job=\"$job\",vkyc_consumer=\"AgentEventKafkaConsumer\"}",
       "legendFormat": "{{vkyc_consumer}}-{{vkyc_topic}}-{{vkyc_event}}"
      }
     ]
    },
    {
     "title": "p95 quantile customer consumer events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "videokyc_event_latency_metric_seconds{application=~\"$application\",uri!~\".*health.*|.*prom.*\",quantile=\"0.95\",job=\"$job\",vkyc_consumer=\"CustomerEventKafkaConsumer\"}",
       "legendFormat": "{{vkyc_consumer}}-{{vkyc_topic}}-{{vkyc_event}}"
      }
     ]
    },
    {
     "title": "p50 agent consumer events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "videokyc_event_latency_metric_seconds{application=~\"$application\",uri!~\".*health.*|.*prom.*\",quantile=\"0.5\",job=\"$job\",vkyc_consumer=\"AgentEventKafkaConsumer\"}",
       "legendFormat": "{{vkyc_consumer}}-{{vkyc_topic}}-{{vkyc_event}}"
      }
     ]
    },
    {
     "title": "p50 customer consumer events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "videokyc_event_latency_metric_seconds{application=~\"$application\",uri!~\".*health.*|.*prom.*\",quantile=\"0.5\",job=\"$job\",vkyc_consumer=\"CustomerEventKafkaConsumer\"}",
       "legendFormat": "{{vkyc_consumer}}-{{vkyc_topic}}-{{vkyc_event}}"
      }
     ]
    },
    {
     "title": "p99 agent consumer events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "videokyc_event_latency_metric_seconds{application=~\"$application\",job=\"$job\",uri!~\".*health.*|.*prom.*\",quantile=\"0.99\",vkyc_consumer=\"AgentEventKafkaConsumer\"}",
       "legendFormat": "{{vkyc_consumer}}-{{vkyc_topic}}-{{vkyc_event}}"
      }
     ]
    },
    {
     "title": "p99 customer consumer events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "videokyc_event_latency_metric_seconds{application=~\"$application\",job=\"$job\",uri!~\".*health.*|.*prom.*\",quantile=\"0.99\",vkyc_consumer=\"CustomerEventKafkaConsumer\"}",
       "legendFormat": "{{vkyc_consumer}}-{{vkyc_topic}}-{{vkyc_event}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\", area=~\"heap\",job=\"videkyc-prod-kubernetes-service-endpoints\"})*100/sum(jvm_memory_max_bytes{application=~\"$application\",instance=~\"$instance\", area=~\"heap\",job=\"videkyc-prod-kubernetes-service-endpoints\"})",
       "legendFormat": "Heap Used in percentage"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\", area=~\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=~\"$application\",instance=~\"$instance\", area=~\"nonheap\"})"
      }
     ]
    },
    {
     "title": "Start Time",
     "type": "stat",
     "description": "Application start time",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=~\"$application\", instance=~\"$instance\",job=\"$job\",environment=\"$environment\",kubernetes_namespace=\"$kubernetes_namespace\"}*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",kubernetes_namespace=\"$kubernetes_namespace\"}",
       "legendFormat": "{{application}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",kubernetes_namespace=\"$kubernetes_namespace\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (system_cpu_usage{instance=~\"$instance\", application=\"$application\",job=\"$job\",environment=\"$environment\",kubernetes_namespace=\"$kubernetes_namespace\"}/system_cpu_count) * 100",
       "legendFormat": "System CPU Usage {{instance}}"
      },
      {
       "expr": "sum by (instance) (process_cpu_usage{instance=~\"$instance\", application=\"$application\",job=\"$job\",environment=\"$environment\"}/system_cpu_count) * 100",
       "legendFormat": "Process CPU Usage {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP requests - Inbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Request per min(TPM)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "round(sum(increase(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health|.*prometheus\"}[1m])) by (uri,method,status))",
       "legendFormat": "{{method}} - {{status}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Request Count - Inbound [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "round(sum(increase(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\"}[$interval])) by (method,uri)) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 2xx & 3xx count [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "round(sum(increase(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\",status=~\"2.+.+|3.+.+\"}[$interval])) by (method,uri))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 4xx count [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "round(sum(increase(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\",status=~\"4.+.+\"}[$interval])) by (method,uri))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 5xx count [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "round(sum(increase(http_server_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\",status=~\"5.+.+\"}[$interval])) by (method,uri))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "P95 Response Time [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method,status,uri) (avg_over_time(http_server_requests_seconds{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*|.*prom.*\", quantile=\"0.95\", status=~\"2.+.+\"}[$interval]))",
       "legendFormat": "{{method}} [{{status}}] {{uri}}"
      }
     ]
    },
    {
     "title": "P99 Response Time [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method,status,uri) (avg_over_time(http_server_requests_seconds{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*|.*prom.*\", quantile=\"0.99\", status=~\"2.+.+\"}[$interval]))",
       "legendFormat": "{{method}} [{{status}}] {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP requests - Outbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outting Request per min(TPM)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "round(sum(increase(http_client_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri=~\"$outbound_uri\"}[1m])) by (uri,method,status))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Request Count - Outbound [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "round(sum(increase(http_client_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\",uri=~\"$outbound_uri\"}[$interval])) by (method,uri))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 2xx & 3xx - Outbound [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "round(sum(increase(http_client_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\",status=~\"2.+.+|3.+.+\",uri=~\"$outbound_uri\"}[$interval])) by (method,uri))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 4xx  - Outbound [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "round(sum(increase(http_client_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\",status=~\"4.+.+\",uri=~\"$outbound_uri\"}[$interval])) by (method,uri))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 5xx - Outbound [$interval]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "round(sum(increase(http_client_requests_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\",status=~\"5.+.+\",uri=~\"$outbound_uri\"}[$interval])) by (method,uri))",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "P95 Response Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.95, http_client_requests_seconds{application=~\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",kubernetes_namespace=\"$kubernetes_namespace\" ,uri!~\".*health.*|.*prom.*\",quantile=~\"0.95\", status=~\"2.+.+\",uri=~\"$outbound_uri\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] {{uri}}"
      }
     ]
    },
    {
     "title": "P99 Response Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.95, http_client_requests_seconds{application=~\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",kubernetes_namespace=\"$kubernetes_namespace\" ,uri!~\".*health.*|.*prom.*\",quantile=~\"0.99\", status=~\"2.+.+\",uri=~\"$outbound_uri\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Records Processed by videokyc Scheduler ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(increase(videokyc_scheduler_total{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\"}[$interval])) by (name, status)"
      }
     ]
    },
    {
     "title": "time taken to execute cron ($interval)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "max by (name, status)(avg_over_time(videokyc_scheduler_seconds_max{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\"}[$interval]))"
      }
     ]
    },
    {
     "title": "cron run count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "(videokyc_scheduler_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\"}) ",
       "legendFormat": " [{{status}}] - {{name}} - {{message}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gauge: Duration of repository invocations",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "topk(5,spring_data_repository_invocations_seconds_max{application=\"$application\",job=\"$job\",environment=\"$environment\",instance=~\"$instance\" ,uri!~\".*health.*\", uri!~\".*prometheus.*\"})",
       "legendFormat": "{{repository}}:{{method}}:{{exception}}:{{state}}"
      }
     ]
    },
    {
     "title": "DB Queries timing",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(spring_data_repository_invocations_seconds_max{application=\"$application\",job=\"$job\",environment=\"$environment\",instance=~\"$instance\" ,uri!~\".*health.*\", uri!~\".*prometheus.*\"}) by (repository,method,state)",
       "legendFormat": "{{repository}}:{{method}}"
      }
     ]
    },
    {
     "title": "DB Queries Invocation per ($interval)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(sum(increase(spring_data_repository_invocations_seconds_count{application=\"$application\",job=\"$job\",environment=\"$environment\",instance=~\"$instance\" ,uri!~\".*health.*\", uri!~\".*prometheus.*\"}[$interval])) by (repository,method))",
       "legendFormat": "{{repository}}:{{method}}"
      }
     ]
    },
    {
     "title": "DB Queries timing",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "\n\nround(sum(increase(spring_data_repository_invocations_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",state!=\"SUCCESS\"}[1m])) by (repository,method,state))",
       "legendFormat": "{{repository}}:{{method}}"
      }
     ]
    },
    {
     "title": "Hikari connections",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(sum(increase(hikaricp_connections_active{application=\"$application\",job=\"$job\",environment=\"$environment\",instance=~\"$instance\" ,uri!~\".*health.*\", uri!~\".*prometheus.*\"}[$interval])) by (repository,method))",
       "legendFormat": "{{repository}}:{{method}}"
      }
     ]
    },
    {
     "title": "DB Queries Latency ($interval)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by (repository,method)(avg_over_time(spring_data_repository_invocations_seconds_sum{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\",uri!~\".*health.*\", uri!~\".*prometheus.*\"}[$interval]))",
       "legendFormat": "{{repository}}:{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by(instance,action,cause)(increase(jvm_gc_pause_seconds_count{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{action}} [{{cause}}] - {{instance}}"
      }
     ]
    },
    {
     "title": "GC  Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (instance,action,cause)(rate(jvm_gc_pause_seconds_sum{application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\"}[$__rate_interval]))/sum by (instance,action,cause)(rate(jvm_gc_pause_seconds_count{ application=\"$application\",environment=\"$environment\",job=\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{action}} [{{cause}}] -{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", job=~\"videkyc-prod-kubernetes-service-endpoints\",instance=~\"$instance\",area=\"nonheap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=~\"$application\",job=~\"videkyc-prod-kubernetes-service-endpoints\",area=\"nonheap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{ application=~\"$application\",job=~\"videkyc-prod-kubernetes-service-endpoints\",instance=~\"$instance\",area=\"nonheap\"})",
       "legendFormat": "Max "
      }
     ]
    },
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", job=~\"videkyc-prod-kubernetes-service-endpoints\",instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=~\"$application\",job=~\"videkyc-prod-kubernetes-service-endpoints\",instance=~\"$instance\",area=\"heap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{ application=~\"$application\", job=~\"videkyc-prod-kubernetes-service-endpoints\",instance=\"$instance\",area=\"heap\"})",
       "legendFormat": "Max "
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{application=~\"$application\", job=~\"videkyc-prod-kubernetes-service-endpoints\", instance=~\"$instance\"}",
       "legendFormat": "Classes Loaded "
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_unloaded_classes_total{application=~\"$application\",job=~\"videkyc-prod-kubernetes-service-endpoints\"}",
       "legendFormat": "Classes Unloaded "
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{ application=~\"$application\",job=\"videkyc-prod-kubernetes-service-endpoints\",id=\"direct\"})",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{ application=~\"$application\", job=\"videkyc-prod-kubernetes-service-endpoints\",id=\"direct\"})",
       "legendFormat": "Capacity Bytes "
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{application=~\"$application\", job=\"videkyc-prod-kubernetes-service-endpoints\"})",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{application=~\"$application\",job=\"videkyc-prod-kubernetes-service-endpoints\"})",
       "legendFormat": "Capacity Bytes "
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_daemon_threads{application=~\"$application\",job=\"videkyc-prod-kubernetes-service-endpoints\"})",
       "legendFormat": "Daemon"
      },
      {
       "expr": "sum(jvm_threads_live_threads{application=~\"$application\", job=\"videkyc-prod-kubernetes-service-endpoints\"})",
       "legendFormat": "Live - {{app_kubernetes_io_name}}"
      },
      {
       "expr": "sum(jvm_threads_peak_threads{application=~\"$application\", job=\"videkyc-prod-kubernetes-service-endpoints\"})",
       "legendFormat": "Peak "
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=~\"$application\", job=\"videkyc-prod-kubernetes-service-endpoints\"}[$__rate_interval])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=~\"$application\",job=\"videkyc-prod-kubernetes-service-endpoints\"}[$__rate_interval])",
       "legendFormat": "promoted "
      }
     ]
    }
   ]
  }
 ]
}